#pragma once

#include "defines.h"
#include "core/log.h"
#include "core/log.cpp"
#include "core/window.h"
#include "platform/windows_window.h"
#include "platform/windows_window.cpp"
#include "core/entry.h"
#include "core/application.h"
#include "core/application.cpp"
#include "core/layer.h"
#include "core/layer.cpp"
#include "core/layer_stack.h"
#include "core/layer_stack.cpp"